export enum Screens {
  Splash = 'Splash',
  Login = 'Login',
  SelectEntity = 'SelectEntity',
  Main = 'Main',
  Notifications = 'Notification',
  MapView = 'MapView',
  Planning = 'Planning',
  Charters = 'Charters',
  CharterDetails = 'CharterDetails',
  Technical = 'Technical',
  Financial = 'Financial',
  Information = 'Information',
  ToDo = 'ToDo',
  Crew = 'Crew',
  QSHE = 'QSHE',
  Settings = 'Settings',
  ChangeRole = 'ChangeRole',
  QRScanner = 'QRScanner',
  Formations = 'Formations',
  PDFView = 'PDFView',
  MeasurementTable = 'MeasurementTable',
}
