export {default as Details} from './Details'
export {default as CargoList} from './CargoList'
export {default as CargoHolds} from './CargoHolds'
export {default as Documents} from './Documents'
export {default as Map} from './Map'
export {default as Actions} from './Actions'
export {default as DraughtCalculator} from './DraugtCalculator'
