export {default as Details} from './Details'
export {default as CargoList} from './CargoList'
export {default as CargoHolds} from './CargoHolds'
export {default as Documents} from './Documents'
export {default as NavLogMap} from './NavLogMap'
